module.exports = [
  { name: "Egg free", icon: "🥚", id: 'egg-free'},
  { name: "Milk free" , icon: "🥛", id: 'milk-free'},
  { name: "Peanut free" , icon: "🥜", id: 'peanut-free'},
  { name: "Shellfish free" , icon: "🦀", id: 'shellfish-free'},
  { name: "Soy free", icon: "🌱", id: 'soy-free'},
  { name: "Sugar free", icon: "🍬", id: 'sugar-free'},
  { name: "Vegetarian", icon: "🟢", id: 'vegetarian'},
  { name: "Gluten free", icon: "🌾", id: 'gluten-free'},
  { name: "Tree Nut free", icon: "🌰", id: 'tree-nut-free'},
  { name: "Meat free", icon: "🥩", id: 'meat-free'},
  { name: "Poultry free", icon: "🍗", id: 'poultry-free'},
  { name: "Fish free", icon: "🐟", id: 'fish-free'},
  { name: "Low sodium", icon: "🧂", id: 'low-sodium'},
  { name: "Vegan", icon: "Ⓥ", id: 'vegan'},
]